"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log("teste");
const a = 1;
console.log(a);
const b = 2;
console.log(b);
const c = 3;
console.log(c);
const d = 4;
console.log(d);
const e = 5;
console.log(e);
const f = 6;
console.log(f);
const g = 7;
console.log(g);
const h = 8;
console.log(h);
const i = 9;
console.log(i);
const j = 10;
console.log(j);
const k = 11;
console.log(k);
const l = 12;
console.log(l);
const m = 13;
console.log(m);
const n = 14;
//# sourceMappingURL=teste.js.map