"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log("teste");
const a = 1;
console.log(a);
const b = 2;
console.log(b);
const c = a + b;
console.log(c);
const d = a * b;
console.log(d);
console.log(c);
console.log(d);
console.log(c + d);
const e = c + d;
console.log(e);
console.log(c + d);
console.log(c + d);
console.log(c + d);
//# sourceMappingURL=teste.js.map